// <auto-generated />
using System;
using LocalDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalDataApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120044605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalDataApi.Models.BLFParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BLFNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoilResistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalLeakage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hysteresis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsulationResistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsulationStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalLeakage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumFlowRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartingCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WithstandVoltageStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BLFParameters");
                });

            modelBuilder.Entity("LocalDataApi.Models.CurrentFlowRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BLFParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Current")
                        .HasColumnType("real");

                    b.Property<float>("FlowRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BLFParameterId");

                    b.ToTable("CurrentFlowRates");
                });

            modelBuilder.Entity("LocalDataApi.Models.PressureFlowRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BLFParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FlowRate")
                        .HasColumnType("real");

                    b.Property<float>("Pressure")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BLFParameterId");

                    b.ToTable("PressureFlowRates");
                });

            modelBuilder.Entity("LocalDataApi.Models.CurrentFlowRate", b =>
                {
                    b.HasOne("LocalDataApi.Models.BLFParameter", null)
                        .WithMany("CurrentFlowRateCurve")
                        .HasForeignKey("BLFParameterId");
                });

            modelBuilder.Entity("LocalDataApi.Models.PressureFlowRate", b =>
                {
                    b.HasOne("LocalDataApi.Models.BLFParameter", null)
                        .WithMany("PressureFlowRateCurve")
                        .HasForeignKey("BLFParameterId");
                });

            modelBuilder.Entity("LocalDataApi.Models.BLFParameter", b =>
                {
                    b.Navigation("CurrentFlowRateCurve");

                    b.Navigation("PressureFlowRateCurve");
                });
#pragma warning restore 612, 618
        }
    }
}
