// <auto-generated />
using System;
using LocalDataApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalDataApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808080622_AddRbacTables")]
    partial class AddRbacTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalDataApi.Domain.Blf.BLFParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BLFNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClosedLoopFluctuation4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoilResistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalLeakage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hysteresis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsulationResistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsulationStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalLeakage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumFlowRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartingCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WithstandVoltageStrength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BLFParameters");
                });

            modelBuilder.Entity("LocalDataApi.Domain.Blf.CurrentFlowRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BLFParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Current")
                        .HasColumnType("real");

                    b.Property<float>("FlowRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BLFParameterId");

                    b.ToTable("CurrentFlowRates");
                });

            modelBuilder.Entity("LocalDataApi.Domain.Blf.PressureFlowRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BLFParameterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("FlowRate")
                        .HasColumnType("real");

                    b.Property<float>("Pressure")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("BLFParameterId");

                    b.ToTable("PressureFlowRates");
                });

            modelBuilder.Entity("LocalDataApi.Domain.Erp.ERPId", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("currentcount")
                        .HasColumnType("int");

                    b.Property<string>("tablecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tablename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tb_control_id", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Erp.ERPUser", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("upwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usercode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tb_control_user", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TargetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime", "Action");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorpDepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LeaderUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CorpDepartmentId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("Path");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Module", "Resource");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsActive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastLoginTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockoutEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginFailCount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifyDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionVersion")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimaryDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrimaryDepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WeChatWorkUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("用户管理", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.BOMStructureProcess", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("制定人")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("制定日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("制定编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("制定说明")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("执行日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("执行状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("执行车间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("BOM结构工序", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.DeliveryPlan", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("交货数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("发运数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("待发数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("销控编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("交货计划", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ExternalProduction", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("仓库名称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单层级")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工序")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工序车间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("生产数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("电压")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("线圈")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("订单数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("需求量")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("分析单号", "货号")
                        .IsUnique()
                        .HasFilter("[分析单号] IS NOT NULL AND [货号] IS NOT NULL");

                    b.HasIndex("排产编号", "货号");

                    b.ToTable("外产_生产", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ExternalProductionBOM", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("产品属性")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("仓库名称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("仓库数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("关联编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("层")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("父级编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("生产数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("父级编号");

                    b.HasIndex("分析单号", "货号");

                    b.ToTable("外产_BOM", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ExternalProductionPickMaterial", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("出库数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("父级编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("需求量")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("分析单号", "货号");

                    b.ToTable("外产_领料", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ExternalProductionShipment", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("发运数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("需求量")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("分析单号", "货号")
                        .IsUnique()
                        .HasFilter("[分析单号] IS NOT NULL AND [货号] IS NOT NULL");

                    b.HasIndex("排产编号", "货号");

                    b.ToTable("外产_发运", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ExternalProductionWarehousing", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("入库数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("需求量")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("分析单号", "货号");

                    b.ToTable("外产_入库", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.InTransitQuantity", b =>
                {
                    b.Property<double?>("在途数")
                        .HasColumnType("float");

                    b.Property<string>("成品货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_甘特图在产量", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.PMCBasicInfo", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("业务员")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("生产类型")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("外销合同基本信息", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.PMCDeliveryReview", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("中文品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("中文规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("物料货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("特殊要求")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("状态")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("生产类型")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("电压")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("线圈货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("状态", "排产编号", "货号");

                    b.ToTable("外产_订单", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.PMCProductInfo", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("中文品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("中文规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("入库数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("发运数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("在产需求量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("实际完成日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("层")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("父编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("电压")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("线圈")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("货号", "合同号", "分析单号", "层");

                    b.ToTable("外销合同产品", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.PMCUserProductInfo", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("中文品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("中文规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("合同单价")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("备注")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("序号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("数量单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("电压")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("货好日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("金额")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("驳回原因")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("创建时间", "合同号", "货号");

                    b.ToTable("外销合同客户产品", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ProductData", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("中文品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("中文规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("产品属性")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("产品类别")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("停用")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("制造方式")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工序名称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("数量单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("生产车间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("产品资料", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ProductDataAssembly", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建人")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("产品资料装配", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ProductDataAssemblyList", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("中间件")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("主编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("主货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("产品资料装配清单", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ProductionDemand", b =>
                {
                    b.Property<double?>("在产需求")
                        .HasColumnType("float");

                    b.Property<string>("成品货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_在产需求量", (string)null);
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.ProductionTypeOverride", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("修改人")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("合同号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("生产类型")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("合同号", "排产编号", "货号")
                        .IsUnique()
                        .HasFilter("[合同号] IS NOT NULL AND [排产编号] IS NOT NULL AND [货号] IS NOT NULL");

                    b.ToTable("生产类型修改", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.SchedulingAnalysis", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析人")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("分析日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("客户简称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("生产方式")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("分析单号")
                        .IsUnique()
                        .HasFilter("[分析单号] IS NOT NULL");

                    b.HasIndex("排产编号");

                    b.ToTable("排产分析单", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.WarehouseGoods", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("仓库名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("单价")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("单位")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("商品属性")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("库存上限")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("库存下限")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("来源")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("订单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("金额")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("仓库货品", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.WarehouseInfo", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("仓库类型")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("名称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("纳入需求计算")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.ToTable("仓库信息", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.WorkOrderSalesControl", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("商品属性")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("在产数量")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("层")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单总数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("已入库数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("生产完成率")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("车间名称")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("配料")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("齐套")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("货号")
                        .IsUnique()
                        .HasFilter("[货号] IS NOT NULL");

                    b.ToTable("工单销控表", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Pmc.WorkOrderSalesControlDetail", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("交货日期")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("入库数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("分析单号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("品名")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("工单单号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("待产数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产用户")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("排产编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("父级编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("生产数")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("规格")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("货号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("父级编号");

                    b.HasIndex("货号", "分析单号")
                        .IsUnique()
                        .HasFilter("[货号] IS NOT NULL AND [分析单号] IS NOT NULL");

                    b.ToTable("工单销控表明细", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.WeChatWork.WechatWorkGroupChat", b =>
                {
                    b.Property<string>("编号")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberUserIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("修改状态")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("创建时间")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("审核过程")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("打印")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户编号")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("用户铭")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("锁定用户")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("编号");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("企业微信群聊", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("LocalDataApi.Domain.Blf.CurrentFlowRate", b =>
                {
                    b.HasOne("LocalDataApi.Domain.Blf.BLFParameter", null)
                        .WithMany("CurrentFlowRateCurve")
                        .HasForeignKey("BLFParameterId");
                });

            modelBuilder.Entity("LocalDataApi.Domain.Blf.PressureFlowRate", b =>
                {
                    b.HasOne("LocalDataApi.Domain.Blf.BLFParameter", null)
                        .WithMany("PressureFlowRateCurve")
                        .HasForeignKey("BLFParameterId");
                });

            modelBuilder.Entity("LocalDataApi.Domain.Blf.BLFParameter", b =>
                {
                    b.Navigation("CurrentFlowRateCurve");

                    b.Navigation("PressureFlowRateCurve");
                });
#pragma warning restore 612, 618
        }
    }
}
