// <auto-generated />
using LocalDataApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LocalDataApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811000000_AddAuthSessions")]
    partial class AddAuthSessions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");
        }
    }
}
